version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    links:
      - backend
    ports:
      - 8080:8080

  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8090:8090
